time quant page
molecula/documentation pull request #238
Opened 2022-10-03 22:28 UTC by gthrone25

adding a detailed time quantum page

2022-10-03 22:28 UTC, gthrone25 commented
@jaffee I'd love your eyes on this when ya can 🙏

2022-10-04 19:14 UTC, jaffee commented on data-modeling-guide/_posts/2022-01-29-time-quantums.md
> +When you don't care about older views and want to reduce your datafootprint over time.
```suggestion
When you don't care about older views and want to reduce the growth of your data footprint over time.
```

2022-10-04 19:16 UTC, jaffee commented on data-modeling-guide/_posts/2022-01-29-time-quantums.md
> +TTL holds the duration for the views created by FeatureBase based on the time quantum and the current time. This means it deletes based on the value of timestamp associated with the value and the cur
```suggestion
TTL holds the duration for the views created by FeatureBase based on the time quantum and the current time. This means it deletes based on the value of timestamp associated with the value and the current time. It does not care when the data is ingested, it only looks at the times associated with the data in time quantum views. Once the TTL duration expires, those views will be deleted. If TTL's value is 0s (default value), the views created based on the time quantum will not be deleted.
```

2022-10-04 19:20 UTC, jaffee commented on data-modeling-guide/_posts/2022-01-29-time-quantums.md
> +TTL removal is set to run when FeatureBase starts and every hour thereafter. This means view deletion is eventually consistent.
```suggestion
TTL removal is (at the time of this writing) set to run when FeatureBase starts and every hour thereafter. This means view deletion is eventually consistent. TTL removal is, in general, not guaranteed to run at any particular time, and you should always use closed time ranges on your queries if you need to guarantee that results older than the TTL don't show up.
```

2022-10-04 19:21 UTC, jaffee commented on data-modeling-guide/_posts/2022-01-29-time-quantums.md
> +A process runs every hour that looks at the views and the current time to see if it has exceeded the TTL set. Each time granularity uses slightly different rules that lead to eventually consistent de
```suggestion
A process runs periodically that looks at the views and the current time to see if they have exceeded the configured TTL. Each view may be deleted at a different time based on its granularity and how long it's been since the end of that view's time range. For Example:
```

2022-10-04 19:26 UTC, jaffee commented on data-modeling-guide/_posts/2022-01-29-time-quantums.md
> +A column with `YMD` has three views for 9/2/2022 with TTL set to `30d`. The 9/2/2022 view is cleared after 30 days, the 9/2022 view is cleared at the end of 10/2022, and the 2022 view is deleted at t
```suggestion
A column with `YMD` has four views for 2022-09-02 (2022, 2022-09, 2022-09-02 and standard) with TTL set to `30d`. The 2022-09-02 view is cleared after 30 days (roughly on 2022-10-02), the 2022-09 view is cleared on October 30, 2022, and the 2022 view is deleted January 30, 2023.

The rule is, if the end of the time range represented by the view is older than the TTL, it can be deleted.
```

2022-10-04 19:26 UTC, jaffee requested changes
made a few suggestions

2022-10-06 19:31 UTC, gthrone25 commented on data-modeling-guide/_posts/2022-01-29-time-quantums.md
> +- "ttl":"1s" is equal to 1 second.
Agree. Changed the example but I'm curious if you think we should even show ms, us, ns? to each's own, but I think it takes away from what you're saying here.

2022-10-06 19:32 UTC, gthrone25 commented on data-modeling-guide/_posts/2022-01-29-time-quantums.md
> +TTL removal is set to run when FeatureBase starts and every hour thereafter. This means view deletion is eventually consistent.
great add! I added a recommendation of 1hr or more but let me know if you disagree

2022-10-06 19:42 UTC, jaffee commented on data-modeling-guide/_posts/2022-01-29-time-quantums.md
> +- "ttl":"1s" is equal to 1 second.
yeah, maybe we should just say you specify the TTL as number of hours... I don't think it makes much sense to use any other units.

2022-10-06 21:17 UTC, gthrone25 commented on data-modeling-guide/_posts/2022-01-29-time-quantums.md
> +- "ttl":"1s" is equal to 1 second.
I deleted them and then realized the default was 0s, which feels weird if not listed... So i pushed a change with up to seconds and smaller cut out. I put a comment to say we actually support more for future users reference. If nothing else, hit me with an approve and I'll merge on in!

2022-10-06 21:18 UTC, jaffee approved these changes

2022-10-06 21:21 UTC, merged