adding SUBSTRING function
molecula/documentation pull request #283
Opened 2022-12-09 21:49 UTC by rachithrr

2022-12-12 19:41 UTC, pokeeffe-molecula requested changes
Few comments in describing parameters

2022-12-12 19:41 UTC, pokeeffe-molecula commented on sql-preview/functions/_posts/2022-12-09-sql-reverse.md
> +The argument `expr` can either be a string column or another string function
I would reword this even more generally. Something like "the argument `expr` is any expression of type `string`", and be inclined to use this everywhere we discuss parameters.

2022-12-12 19:41 UTC, pokeeffe-molecula commented on sql-preview/functions/_posts/2022-12-09-sql-substring.md
> +The starting index of the substring in the input string, starting at zero. startIndex must be an integer.
Same thing here - let's talk types i.e. "startIndex can be any expression of of type `int`"

2022-12-12 19:41 UTC, pokeeffe-molecula commented on sql-preview/functions/_posts/2022-12-09-sql-substring.md
> +The length of the substring to extract. length must be a positive integer
And here - let's talk types i.e. "length is any expression of of type `int`"

2022-12-12 19:49 UTC, gthrone25 reviewed
@rachithrr Looks good! Just a couple of comments to address. It looks like the structural piece of this was already merged in last week, so no turning back now :). @ljsinclair will most likely restructure in the near future.

2022-12-12 22:41 UTC, ljsinclair requested changes
Hi there,
Can you also drop the heading levels by 1 please? Start the page at h2 (##) and subsequent headings are h3 (###)

2022-12-13 18:56 UTC, gthrone25 approved these changes
Looks good! Approving and will merge once @pokeeffe-molecula and @ljsinclair approve. Note might be better just to "comment" (as opposed to request change) on reviews in the future otherwise we need all 3 approvals before merging.

2022-12-13 23:27 UTC, pokeeffe-molecula approved these changes
lgtm

2022-12-14 00:11 UTC, ljsinclair approved these changes
super :) Thanks

2022-12-14 00:14 UTC, merged