Adding documentation for string fun UPPER
molecula/documentation pull request #284
Opened 2022-12-12 21:20 UTC by HHans09

2022-12-12 22:38 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-12-sql-upper.md
> +| **ℹ️NOTE** | This page contains information that only applies to SQL Preview functionality (more information [here](/sql-preview/sql-preview)). Additionally, this page represents a work in progress
We can leave this out because the file is found under "SQL-Preview"

2022-12-12 22:38 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-12-sql-upper.md
> +### UPPER()
Start the headings at h2 or "##"

2022-12-12 22:39 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-12-sql-upper.md
> +#### Syntax
Make these headings h3 or ###

2022-12-12 22:40 UTC, ljsinclair requested changes
Hi there,
Just a couple of changes to make here
Thanks

2022-12-13 16:35 UTC, HHans09 commented on sql-preview/functions/_posts/2022-12-12-sql-upper.md
> +| **ℹ️NOTE** | This page contains information that only applies to SQL Preview functionality (more information [here](/sql-preview/sql-preview)). Additionally, this page represents a work in progress
Done

2022-12-13 16:35 UTC, HHans09 commented on sql-preview/functions/_posts/2022-12-12-sql-upper.md
> +### UPPER()
Updated

2022-12-13 16:36 UTC, HHans09 commented on sql-preview/functions/_posts/2022-12-12-sql-upper.md
> +#### Syntax
Updated

2022-12-14 00:56 UTC, gthrone25 reviewed
@HHans09 looks good to me except you'll have to resolve a conflict as @rachithrr touched 2022-12-09-sql-string-functions.md as well. @rachithrr my only question is why we have two different syntaxes for the "Arguments" section in the Substring (<argument> <description>) and Reverse (<description>) pages. I think we should standardize on one of those.

2022-12-14 18:36 UTC, rachithrr commented
@gthrone25 , yes. We shall follow the SubString() going forward. I'll make the changes for the Reverse() in my next pr.

2022-12-14 19:10 UTC, gthrone25 approved these changes
LGTM

2022-12-14 19:58 UTC, HHans09 commented
> Hi there, Just a couple of changes to make here Thanks

changes made

2022-12-14 22:47 UTC, ljsinclair requested changes
The page is called "UPPER()" so there's no need to add a heading 2 at the top. This means once that's gone, all the other headings go down a level

2022-12-15 01:55 UTC, ljsinclair approved these changes
for the win! thanks :)

2022-12-15 15:53 UTC, merged