added htmlproofer link check
molecula/documentation pull request #288
Opened 2022-12-13 00:01 UTC by ljsinclair

Just the htmlproofer link check

2022-12-13 15:19 UTC, gthrone25 requested changes
Looks like this is missing the bash script to run? I ran bundle and nothing was generated with that name

2022-12-15 18:24 UTC, gthrone25 commented
> Looks like this is missing the bash script to run? I ran bundle and nothing was generated with that name

@ljsinclair ?

2022-12-15 22:57 UTC, ljsinclair commented
Fixed. How much to keep this dumb mistake between us? >.<

2022-12-15 23:07 UTC, gthrone25 commented on README.md
> +bash check-links.sh
@ljsinclair I followed the instructions above and get the following error:

> bundler: failed to load command: htmlproofer (/usr/local/bin/htmlproofer)

advice?

2022-12-15 23:10 UTC, gthrone25 commented on README.md
> +bash check-links.sh
Nevermind I see it. This check is for x86 architecture only and won't work on amd (mac). Not so sure we should go this route now...

> /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/extension.rb:7:in `require_relative': dlopen(/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64h))) - /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.3-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle (LoadError)

2022-12-15 23:15 UTC, ljsinclair commented on README.md
> +bash check-links.sh
Oh, I'm sorry about that. I had no idea that'd occur :(

2022-12-15 23:15 UTC, ljsinclair commented on README.md
> +bash check-links.sh
The python one still works, it's just an alternate method

2022-12-15 23:19 UTC, ljsinclair commented on README.md
> +bash check-links.sh
added processor types to the 2x broken link checks to clarify what's going on

2022-12-16 00:07 UTC, ljsinclair commented
closing this because it turns out htmlproofer only runs on x86 systems.

2022-12-16 00:07 UTC, closed without merging