Adding documentation for Trim funcs - Trim, Rtrim & LTrim
molecula/documentation pull request #291
Opened 2022-12-14 21:55 UTC by HHans09

2022-12-15 01:57 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-14-sql-ltrim.md
> +## LTRIM()
You don't need a leading heading because the page gets named automatically.
Removing this means all the following headings can go down a level :)

2022-12-15 15:56 UTC, HHans09 commented on sql-preview/functions/_posts/2022-12-14-sql-ltrim.md
> +## LTRIM()
Updated

2022-12-15 18:35 UTC, gthrone25 requested changes
@HHans09 Looks good but this needs to conform to the standards Rachith is using (see comments) as well use higher headings for all sections in all new pages.

2022-12-15 18:35 UTC, gthrone25 commented on sql-preview/functions/_posts/2022-12-14-sql-ltrim.md
> +The argument `expr` is any expression of type string
Please match the syntax Rachith has standardized to. A couple example can be seen in this PR: https://github.com/molecula/documentation/pull/290/files#diff-bb30d9ad93adca05c9113d898dbfb1d4b0afe1d5c0f602f4b206a27fdfcd160c

2022-12-15 18:35 UTC, gthrone25 commented on sql-preview/functions/_posts/2022-12-14-sql-rtrim.md
> +The argument `expr` is any expression of type string
Please match the syntax Rachith has standardized to. A couple example can be seen in this PR: https://github.com/molecula/documentation/pull/290/files#diff-bb30d9ad93adca05c9113d898dbfb1d4b0afe1d5c0f602f4b206a27fdfcd160c

2022-12-15 18:35 UTC, gthrone25 commented on sql-preview/functions/_posts/2022-12-14-sql-trim.md
> +The argument `expr` is any expression of type string
Please match the syntax Rachith has standardized to. A couple example can be seen in this PR: https://github.com/molecula/documentation/pull/290/files#diff-bb30d9ad93adca05c9113d898dbfb1d4b0afe1d5c0f602f4b206a27fdfcd160c

2022-12-15 18:35 UTC, gthrone25 commented on sql-preview/functions/_posts/2022-12-14-sql-ltrim.md
> +#### Syntax
We need to lose a # on all of the headings in these pages based on @ljsinclair previous reviews

2022-12-15 18:58 UTC, HHans09 commented on sql-preview/functions/_posts/2022-12-14-sql-ltrim.md
> +#### Syntax
as per @ljsinclair : You don't need a leading heading because the page gets named automatically.
Removing this means all the following headings can go down a level :)

2022-12-15 20:09 UTC, gthrone25 commented on sql-preview/functions/_posts/2022-12-14-sql-ltrim.md
> +#### Syntax
Ya I'm thinking she misspoke and meant to say up a level. @ljsinclair can you clarify?

2022-12-15 22:16 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-14-sql-ltrim.md
> +### Syntax
So the `##LTRIM()` heading can be removed.
Headings that follow can become H2 ``## Syntax`, etc

2022-12-15 22:17 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-14-sql-rtrim.md
> +The argument `expr` is any expression of type string
You can remove the leading heading `## RTRIM...` and reduce all the headings by one `#`

2022-12-15 22:18 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-14-sql-trim.md
> +The argument `expr` is any expression of type string
Again, no leading heading required so remove `## TRIM` and reduce everything else by one heading level

2022-12-15 22:19 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-14-sql-trim.md
> +## LTRIM()
Is this a duplication of 2022-12-14-sql-ltrim.md?

2022-12-15 22:19 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-14-sql-trim.md
> +## RTRIM()
Is this a duplication of 2022-12-14-sql-rtrim.md?

2022-12-15 22:54 UTC, gthrone25 commented on sql-preview/functions/_posts/2022-12-14-sql-trim.md
> +The argument `expr` is any expression of type string
I'm only referring to the standardization for items in the arguments section to clear

2022-12-15 22:55 UTC, gthrone25 commented on sql-preview/functions/_posts/2022-12-14-sql-rtrim.md
> +The argument `expr` is any expression of type string
I'm only referring to the standardization for items in the arguments section to clear

2022-12-15 22:55 UTC, gthrone25 commented on sql-preview/functions/_posts/2022-12-14-sql-ltrim.md
> +The argument `expr` is any expression of type string
I'm only referring to the standardization for items in the arguments section to clear

2022-12-16 00:08 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-14-sql-ltrim.md
> +#### Syntax
Remove a # is what I meant. By down I meant remove.

2022-12-16 16:07 UTC, HHans09 commented on sql-preview/functions/_posts/2022-12-14-sql-trim.md
> +## LTRIM()
I started with one doc for all the trims but newer commits have separate files for trim, Ltrim & Rtrim

2022-12-16 16:07 UTC, HHans09 commented on sql-preview/functions/_posts/2022-12-14-sql-trim.md
> +## RTRIM()
I started with one doc for all the trims but newer commits have separate files for trim, Ltrim & Rtrim

2022-12-16 16:10 UTC, HHans09 commented on sql-preview/functions/_posts/2022-12-14-sql-ltrim.md
> +### Syntax
Updated

2022-12-16 16:10 UTC, HHans09 commented on sql-preview/functions/_posts/2022-12-14-sql-ltrim.md
> +#### Syntax
Updated headings as per referenced page

2022-12-16 16:11 UTC, HHans09 commented on sql-preview/functions/_posts/2022-12-14-sql-trim.md
> +The argument `expr` is any expression of type string
Updated headings as per referenced page

2022-12-16 16:11 UTC, HHans09 commented on sql-preview/functions/_posts/2022-12-14-sql-rtrim.md
> +The argument `expr` is any expression of type string
Updated headings as per referenced page

2022-12-16 16:11 UTC, HHans09 commented on sql-preview/functions/_posts/2022-12-14-sql-ltrim.md
> +The argument `expr` is any expression of type string
Updated headings as per referenced page

2022-12-16 16:58 UTC, gthrone25 commented on sql-preview/functions/_posts/2022-12-14-sql-ltrim.md
> +The argument `expr` is any expression of type string
still missing this:

> _expr_ 

see https://docs.featurebase.com/sql-preview/functions/sql-reverse#arguments as an example

2022-12-16 17:06 UTC, HHans09 commented on sql-preview/functions/_posts/2022-12-14-sql-ltrim.md
> +The argument `expr` is any expression of type string
Updated in latest commit

2022-12-16 17:14 UTC, gthrone25 approved these changes
LGTM!

2022-12-16 17:14 UTC, merged