added keyed set to stringset
molecula/documentation pull request #292
Opened 2022-12-14 23:18 UTC by ljsinclair

added datatype mapping from sql-datatypes
deleted sql-datatypes
deleted cloud-data-modeling data-types

2022-12-14 23:23 UTC, gthrone25 requested changes
@ljsinclair we need to give string, id, and idset pages the same treatment since you added this for the stringset page

2022-12-14 23:23 UTC, gthrone25 commented on sql-preview/data-types/_posts/2022-10-25-data-type-stringset.md
> +* STRINGSET has a keyed set internal datatype
> * STRINGSET has a `keyed set` internal datatype

2022-12-15 02:09 UTC, ljsinclair commented on sql-preview/data-types/_posts/2022-10-25-data-type-stringset.md
> +* STRINGSET has a keyed set internal datatype
Sorted and committing :D

2022-12-15 20:17 UTC, gthrone25 reviewed
All looks good except 3 datatypes pages are still missing their updates like stringset got:
| string | keyed mutex |
| id | mutex |
| idset | set |

2022-12-15 22:54 UTC, ljsinclair commented
Fixed the internal data types and tidied the explanations

2022-12-15 23:17 UTC, gthrone25 reviewed
@ljsinclair two typos

2022-12-15 23:17 UTC, gthrone25 commented on sql-preview/data-types/_posts/2022-11-10-data-type-idset.md
> +* has a `mutex` internal data type
needs to be `set`

2022-12-15 23:17 UTC, gthrone25 commented on sql-preview/data-types/_posts/2022-10-30-data-type-string.md
> +* has a `keyed-mutex` internal data type
no `-` to be consistent with table

2022-12-15 23:49 UTC, ljsinclair commented on sql-preview/data-types/_posts/2022-11-10-data-type-idset.md
> +* has a `mutex` internal data type
done

2022-12-15 23:50 UTC, ljsinclair commented on sql-preview/data-types/_posts/2022-10-30-data-type-string.md
> +* has a `keyed-mutex` internal data type
done

2022-12-15 23:53 UTC, gthrone25 approved these changes
LGTM

2022-12-15 23:53 UTC, merged