CHAR()
molecula/documentation pull request #297
Opened 2022-12-16 22:02 UTC by rachithrr

2022-12-19 02:04 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-16-sql-char.md
> +`char()` returns the string based on the ASCII code.
Like for ASCII() I'm wondering what the purpose of this is, and the benefit to the user.

2022-12-19 02:04 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-16-sql-char.md
> ++-----+----------+------+
If this is the result of the create table, insert, etc then can we make this clearer?

2022-12-19 02:16 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-16-sql-char.md
> +`Char()` function returns the string based on the ASCII code.
"Returns the string based on the ASCII code"
* the ASCII code of what? 
* Do you mean someone sticks an ASCII code into the brackets and the function outputs the equivalent string?
* If so, which code are we talking about (https://www.ascii-code.com/)

Why would a user want to use this function?
What circumstances is a function like this useful?
* It's ok to point out to existing docs on things like this, e.g., https://www.w3schools.com/sql/func_sqlserver_char.asp

2022-12-19 02:16 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-16-sql-char.md
> +_code_
A couple of things here, and it's just something I've noticed:

* Is there a reason you're using underscores around the argument instead of just a code block?
* I don't understand what's meant by "The ASCII number code to return the string for". This could be a typo?

2022-12-19 02:22 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-16-sql-char.md
> +The ASCII number code to return the string for. The argument `code` is any expression of type `int`.
In the examples you're using "asciicode" instead of code. I suspect this would be clearer than what's here in the syntax?
And again, which asciicode are we talking about?
Additionally, I'm unsure what's meant by "...The argument `code` is any expression of type `int`..." If it's an expression how can it be an argument?
FYI, I may be getting myself confused :D

2022-12-19 02:26 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-16-sql-char.md
> +select _id, segment, char(asciicode) as code from segments;
Points of confusion: using `asciicode` as the source column and `code` for the resulting index.
* code is referred to in the syntax and arguments
* asciicode is what's being translated by char()
* perhaps there's a way to explain these without referring to the arguments?

2022-12-19 02:27 UTC, ljsinclair requested changes
Some points of confusion to discuss :)

2022-12-20 22:17 UTC, gthrone25 commented on sql-preview/functions/_posts/2022-12-16-sql-char.md
> ++-----+----------+------+
It's the result of the select statement. This matches the existing syntax of the other pages that we previously approved, so I'm gonna say this is ok 🥊

2022-12-20 22:34 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-16-sql-char.md
> ++-----+----------+------+
Yeah, ok. So that's something I'll fix once I get to it :)

2023-01-13 13:35 UTC, rachithrr commented
Yes, you are right. The usage of `code` is a bit confusing. 

We were using `expression of type int`, to represent that the fact that the argument can be straight up integer, or you can also insert another function that returns an integer. For example, CHAR(2) == CHAR(LEN("gg"))

This takes an integer and returns the `symbol` as in https://www.ascii-code.com/

In essence, it has to work similar to https://learn.microsoft.com/en-us/sql/t-sql/functions/char-transact-sql?view=sql-server-ver16

2023-01-17 23:20 UTC, ljsinclair approved these changes
looks good to me :)

2023-01-17 23:20 UTC, merged