ASCII()
molecula/documentation pull request #298
Opened 2022-12-16 22:15 UTC by rachithrr

2022-12-16 22:29 UTC, rachithrr commented
merge after https://github.com/molecula/featurebase/pull/2378/files

2022-12-19 01:58 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-16-sql-ascii.md
> +`ascii()` returns the ASCII value. If the evaluated expression `expr` contains more than one character, returns the ascii value of the first character.
Am I right in thinking `ascii() returns the ascii value of the evaluated expression? (if so, need to make this clearer).

With the second sentence, I'm wondering what the benefit of `ascii()` actually is to an end-user. This should be made clearer in the opening paragraph.

2022-12-19 02:01 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-16-sql-ascii.md
> +```sql
What's the result of these SQL statements?

2022-12-19 02:01 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-16-sql-ascii.md
> ++-----+----------+
Or is this the result? In which case, need to make this clearer please :D

2022-12-19 02:02 UTC, ljsinclair requested changes
Hi there, some comments on this mainly around clarification :)

2022-12-20 22:20 UTC, gthrone25 commented on sql-preview/functions/_posts/2022-12-16-sql-ascii.md
> ++-----+----------+
@ljsinclair we previously approved a good amount of pages that already uses this format. I think it's fine, as select is the only statement here that returns a result set.

2022-12-20 22:36 UTC, ljsinclair commented on sql-preview/functions/_posts/2022-12-16-sql-ascii.md
> ++-----+----------+
No worries, I'll fix when I get to the edits on the SQL pages

2023-01-13 15:53 UTC, rachithrr commented on sql-preview/functions/_posts/2022-12-16-sql-ascii.md
> +`ascii()` returns the ASCII value. If the evaluated expression `expr` contains more than one character, returns the ascii value of the first character.
Evaluated expression means that the argument can be any function that evaluates to a string. 
*With the new patch, restricting the length of string to 1 based on Pat's suggestion to keep it restricted.  We might add the ability to pass string of length > 1 in the future.

2023-01-16 04:23 UTC, ljsinclair approved these changes

2023-01-16 04:23 UTC, merged