Cloud users
molecula/documentation pull request #300
Opened 2022-12-23 08:00 UTC by ljsinclair

Okay, so this is the complete documentation for Configure and covers everything under:
* Organization settings
* Manage users
* User profile (new nav item "My profile" at the bottom of the cloud nav links)

There are quite a few files here, all new content.

When complete, the `/cloud/cloud-configuration/22-04-01-users.md` page will be deleted

2023-01-03 19:43 UTC, gthrone25 requested changes
@ljsinclair reviewed! A couple of question and comments throughout :). I think my only question overall is knowing what your thinking is on what the "My Account" section should contain and why it's outside of configuration.

2023-01-03 19:43 UTC, gthrone25 commented on cloud/my-account/_posts/2022-12-10-cloud-user-move.md
> +Active FeatureBase users may be invited to join a different organization.
> FeatureBase users may be invited to join a different organization.

regardless of status, users can be invited to a new org

2023-01-03 19:43 UTC, gthrone25 commented on cloud/my-account/_posts/2022-12-10-cloud-user-move.md
> +WARNING: Accepting the move means you **cannot** login to your original organization.
> WARNING: Accepting the move means you **cannot** access your original organization.

2023-01-03 19:43 UTC, gthrone25 commented on cloud/my-account/_posts/2022-12-20-cloud-user-activate-account.md
> +FeatureBase users are invited to join an organization via email.
This is unless you sign up. Does this need to be "accept invitations as a new user"? If your account already exists or your are going through signup, this is slightly different.

2023-01-03 19:43 UTC, gthrone25 commented on _data/navigation.yml
> +      - title: My account
Not sure I understand why this isn't within configuration. Does this need to be a heading outside of configuration?

2023-01-03 22:49 UTC, ljsinclair commented on _includes/cloud/cloud-user-admin-role-needed.md
> +You will need an owner or Administrator account to perform these steps
Ok, yeah, I can understand that :D

2023-01-03 22:49 UTC, ljsinclair commented on _includes/cloud/cloud-user-notification-msg.md
> +## User notifications
I'll double-check. Might be one from earlier edit :)

2023-01-03 22:51 UTC, ljsinclair commented on _includes/cloud/cloud-user-roles.md
> +| User role privileges | Administrator role privileges |
Yeah, I'm all for that. This was just a shorthand for the current situation because there wasn't much on one side.

2023-01-03 22:52 UTC, ljsinclair commented on _includes/unicode-icons.md
> +## Unicode icons used in help
It's a reference for myself so I know what's going on. Not in the readme because that's massive and unwieldly (i.e., another endless scroll article). If I call it "readme" in the include then it loses meaning.

2023-01-03 23:38 UTC, gthrone25 commented on _includes/cloud/cloud-summary-billing-contact.md
> +The Billing contact is the primary point of contact for billing, and is sent FeatureBase invoices which include your organization name and address.
That's not really figured out yet... Today it's actually just manual work between us and the customer

2023-01-03 23:43 UTC, gthrone25 commented on _includes/unicode-icons.md
> +## Unicode icons used in help
ok so it's going to be removed eventually? Maybe we can name it with a DELETE or something in the title?

2023-01-04 00:03 UTC, ljsinclair commented on _data/navigation.yml
> +      - title: My account
The user should be able to find actions for their account without having to dive thru subdirectories. From their point of view it's *their* account, not a configuration step. Plus, the account view is accessed via the icon at top right, not the config menu (yes, I know it can **also** be accessed via the config menu but the past 20 years of UI design has user account settings in the upper corners) :D

2023-01-05 04:20 UTC, ljsinclair commented on _includes/cloud/cloud-user-admin-role-needed.md
> +You will need an owner or Administrator account to perform these steps
Changed to "Administrator role" and "owner" has been removed :)

2023-01-05 04:26 UTC, ljsinclair commented on _includes/cloud/cloud-user-notification-msg.md
> +## User notifications
It was from an earlier edit. The information was rolled into the cloud org summary include file which was kind of the point, to let the admin know what the details are actually used for.

2023-01-05 04:28 UTC, ljsinclair commented on _includes/cloud/cloud-user-profile-summary.md
> +All users can view their user profile, change their first and last name and reset their password.
Good catch. I suspect I was going to use it in a "user account home" page, but there really isn't the need

2023-01-05 05:09 UTC, ljsinclair commented on _includes/cloud/cloud-user-roles.md
> +By default all accounts are created with the **User** role.
I have overhauled this page totally so it'll need another review :D

2023-01-05 05:10 UTC, ljsinclair commented on _includes/cloud/cloud-user-roles.md
> +| User role privileges | Administrator role privileges |
Totally overhauled :)

2023-01-05 05:10 UTC, ljsinclair commented on _includes/unicode-icons.md
> +## Unicode icons used in help
Removed and turned into a help-on-help page in featurebase-docs help

2023-01-05 06:53 UTC, ljsinclair commented on _includes/cloud/cloud-user-roles.md
> +| Read-only access to query data in the system | Administrators can perform all actions available to the account owner, including:<br/>* Manage databases<br/>* Manage tables<br/>* Ingest data<br/>* M
Fixed the account owner/admin problem.
Have replied to your comments on https://molecula.atlassian.net/browse/DOCS-135
In short, I'm confused about the need for a "user" role that can do 90% of what an Admin can do... It seems strange?

2023-01-05 06:53 UTC, ljsinclair commented on _includes/cloud/cloud-user-roles.md
> +| Read-only access to query data in the system | Administrators can perform all actions available to the account owner, including:<br/>* Manage databases<br/>* Manage tables<br/>* Ingest data<br/>* M
On the other hand, it simplifies the roles/privileges tables because the only difference is in the Organization/User management.

2023-01-05 22:34 UTC, gthrone25 commented on _includes/cloud/cloud-user-admin-role-needed.md
> +You will need an owner or Administrator account to perform these steps
Still shows the same for me

2023-01-06 02:50 UTC, ljsinclair commented on _includes/cloud/cloud-user-roles.md
> +| Read-only access to query data in the system | Administrators can perform all actions available to the account owner, including:<br/>* Manage databases<br/>* Manage tables<br/>* Ingest data<br/>* M
I've sorted this out in a series of tables which revealed there's a bit more to the roles than I realised.

So good news really :)

2023-01-06 08:00 UTC, ljsinclair commented on cloud/cloud-configuration/_posts/2022-11-25-cloud-org-address.md
> +{% include /cloud/cloud-user-admin-role-needed.md %}
Yes it's meant to be on the same line :)
No period required because none of the rest of the bullet points have one.
I admit I'm not consistent about this mind you.

2023-01-06 08:02 UTC, ljsinclair commented on cloud/my-account/_posts/2022-12-20-cloud-user-activate-account.md
> +FeatureBase users are invited to join an organization via email.
I've rejigged the page so it makes this a bit clearer.
Let me know what you think :)

2023-01-06 08:05 UTC, ljsinclair commented
Hi @gthrone25 
Wow this one took a while to get everything in shape.
I've made a bunch of changes that fix the issues you've brought up, and make things *Moar Clearful* (technical term)
FYI, I've separated the "My account" content because from the end-user POV, we're talking about **their** account, not a configuration action.
Technically it's configuration, but most of it takes place by clicking top right and going thru the profile settings that way.
Have fun with it. I know I did ;)
L.

2023-01-06 22:06 UTC, gthrone25 approved these changes
@ljsinclair looks good and approving but made the following changes:

1. Removed everything you just added for Docker. With the upcoming migration, I'm not sure why we're pushing that here. If you want in this repo, please don't add it here but in another PR
2. Updated tables that have role specific titles (ie an admin named column) to use a structure that can scale when more roles are introduced
3. Removed any new additions for data sources. They are going away in a week or two, so I'm avoiding near term clean up work. Feel free to keep this mindset about data sources for cloud :). I'll be purging soon.
4.  Dead links (5 or so). I think you put them in the other PR, so I'm not fixing to avoid merge conflicts, but please change if I'm off there.
5. A couple small things

Feel free to either merge this in or comment on any of my commit changes. Otherwise have a good weekend!

2023-01-09 04:00 UTC, ljsinclair commented on README.md
> +## Local build
This was just so I could use docker to build locally rather than bouncing over to AWS. My bad >.<

2023-01-09 04:47 UTC, ljsinclair commented
I'm just moving stuff across to a new repo because of the rebase issue.
If there's new roles/privs coming in the next few weeks/month, then fine, I'll step off the hill. 
But if not I'm concerned it's just not as clear anymore. And one more column won't actually make that much difference to the table as a whole.
The other point to make is that any more than 5-6 columns in a table on the web will render badly.
So come the point where more roles and privs arrive, I'd be redesigning the whole thing anyway. Possibly into individual include files per role. But that remains to be seen.

2023-01-10 00:15 UTC, ljsinclair commented
Closing this because it's merged in separate PR

2023-01-10 00:15 UTC, closed without merging