documentation for sql func charindex
molecula/documentation pull request #310
Opened 2023-01-19 18:17 UTC by HHans09

2023-01-20 16:14 UTC, gthrone25 requested changes
This and replicate needs to be added to /sql-preview/sql-string-functions. You can add that to just this PR so there are no merge conflicts. I'm a little confused by this function as it seems to be the only one that starts indexing at 1 instead of 0. Is this really how this works?

2023-01-20 16:14 UTC, gthrone25 commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +_position_ *(optional)* (Default value : 1)
Shouldn't this be 0? Other positions for string functions start at 0, so it seems weird this wouldn't.

2023-01-20 16:14 UTC, gthrone25 commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +|   1 | 3        |
Isn't this 2? or does indexing really start with 1 here?

2023-01-20 16:14 UTC, gthrone25 commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +|   1 | 6        |
Again, I'd expect 5 to be the return here

2023-01-20 16:15 UTC, HHans09 commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +_position_ *(optional)* (Default value : 1)
SQL starts the position as 1 instead of 0 so to match that we are doing the same thing. Position starts at 1

2023-01-20 16:16 UTC, HHans09 commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +|   1 | 3        |
Matching SQL outcome, since position starts at 1 so index comes out to be 3

2023-01-20 16:16 UTC, HHans09 commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +|   1 | 6        |
Matching SQL outcome, since position starts at 1 so index comes out to be 6

2023-01-20 16:24 UTC, gthrone25 commented
@HHans09 if that's the case, why do these start at 0?  
https://docs.featurebase.com/sql-preview/functions/sql-stringsplit#stringsplit
https://docs.featurebase.com/sql-preview/functions/sql-substring

2023-01-23 17:23 UTC, gthrone25 commented
@HHans09 just checking on my Q above so we can close these out

2023-01-23 18:10 UTC, HHans09 commented
> @HHans09 just checking on my Q above so we can close these out

Working on standardizing the process of starting position from 0.. Updating code and will update documentation accordingly

2023-01-23 18:11 UTC, HHans09 commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +|   1 | 6        |
Updating code to start position from 0

2023-01-23 18:11 UTC, HHans09 commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +|   1 | 3        |
Updating code to start position from 0

2023-01-23 19:05 UTC, gthrone25 commented
> > @HHans09 just checking on my Q above so we can close these out
> 
> Working on standardizing the process of starting position from 0.. Updating code and will update documentation accordingly

ah ok just tag me whenever. Woohoo standardization 🥳

2023-01-25 12:26 UTC, ljsinclair approved these changes
Looks fine to me :)

2023-01-31 00:48 UTC, ljsinclair commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +charindex(substring,expr,position)
Can we get more detail in the syntax because this doesn't appear to match what's in the example.

```
select _id, charindex('is',segment) as charindex from segments;
```

Maybe I'm showing my inexperience, but there's  `segment` in the brackets where the substring is defined, plus `segments` on the end as the position?

It might help if the column was named something different too -- just in case these terms aren't actually related. And even if they are. Ultimately I'm finding the example confusing

2023-01-31 00:51 UTC, ljsinclair commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +The input string where substring needs to be searched. The argument `expr` is any expression of type `string`.
Low priority fix -- `_expr_` is fully explained here:
http://docs.featurebase.com/sql-preview/sql-operators-and-expressions#expr
It'd be just as easy to link to that page than explain this every single time
You'd leave anything specific to **this** function in the page of course :D

2023-01-31 00:52 UTC, ljsinclair commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +## Remarks
Low priority fix -- In all the SQL I've seen so far, there's **never** been any remarks. Perhaps this could be omitted?

2023-01-31 00:53 UTC, ljsinclair commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +charindex(substring,expr,position)
Apologies, I can't edit the comment. Segments is the table, segment is the column. This is confusing. Can we name one of these something else please because it confuses the SQL example

2023-01-31 16:45 UTC, HHans09 commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +charindex(substring,expr,position)
Table name updated to 'customers'

2023-01-31 20:12 UTC, gthrone25 requested changes
@HHans09 just checking in that this is still waiting on changes to codebase?

2023-01-31 20:12 UTC, gthrone25 commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +The input string where substring needs to be searched. The argument `expr` is any expression of type `string`.
@ljsinclair this is something you can take on across all of the string pages after this is merged in.

2023-01-31 20:12 UTC, gthrone25 commented on sql-preview/functions/_posts/2023-01-18-sql-charindex.md
> +## Remarks
Also something you can change if you see fit across all pages, but let's not have her make this to one page and change the standardization across pages

2023-01-31 20:18 UTC, HHans09 commented
> @HHans09 just checking in that this is still waiting on changes to codebase?

Code is updated and merged. I have updated the docs to reflect that as well

2023-02-01 02:25 UTC, ljsinclair approved these changes
Make it so, warp speed and all that :D

2023-02-01 23:42 UTC, ljsinclair commented
FYI this content added to https://github.com/FeatureBaseDB/featurebase-docs/tree/new-functions and will be merged when this is approved/merged

2023-02-03 14:38 UTC, gthrone25 approved these changes
@HHans09 looks good! Still missing my first comment:

> This and replicate needs to be added to /sql-preview/sql-string-functions. 

I'm going to approve this so you can merge and avoid conflicts, but please open up a new PR and Ill approve it

2023-02-03 16:30 UTC, merged