Implement FORMAT()
molecula/documentation pull request #315
Opened 2023-01-27 16:03 UTC by rachithrr

This works the same way as the print function works.

2023-01-27 19:11 UTC, ljsinclair approved these changes
looks good to me :)

2023-01-27 19:15 UTC, gthrone25 requested changes
Is it possible to get  some more examples? ie Boolean and string relationship might be nice to see what the string representation is. Are there any known combinations that won't work? Can you use IDSET and STRINGSETs with these?

2023-01-31 00:04 UTC, ljsinclair reviewed
Molto bene! Makeit so I say :D

2023-01-31 00:18 UTC, ljsinclair requested changes
Can I just ask now I've really looked at the SQL whether we can also define the additional arguments in the syntax, e.g., 

`"%s -> #%x"` and "`(`id=%d, time =%v...` etc

These may be wildcards (?) that can be used elsewhere too, so if that's the case, I'll set them up as reusable content then insert them where needed. I will need guidance on this though :D

2023-01-31 00:56 UTC, ljsinclair commented on sql-preview/functions/_posts/2023-01-26-sql-format.md
> +select _id, format("%s -> #%x", segment, value) as segment from segments;
Here's the select I'm talking about in my earlier comment.

There's things that aren't defined in the Syntax that shuld be so users know how to use the function.
And as I say, if the `-> #%x` is some kind of known wildcard or prefix or whatnot, then they need to be clearly defined somewhere in the docs, even if it's a hyperlink out to somewhere like w3schools where they're fully defined.

2023-01-31 00:56 UTC, ljsinclair commented on sql-preview/functions/_posts/2023-01-26-sql-format.md
> +select format('id = %d , time = %v , ids = %d, strings = %s', _id, time, ids, strings) as description from segments;
Here's the other instance of the "not quite clear syntax running into actual examples" :D

2023-01-31 01:09 UTC, rachithrr commented on sql-preview/functions/_posts/2023-01-26-sql-format.md
> +select _id, format("%s -> #%x", segment, value) as segment from segments;
The %x is the standard format specifier for hexadecimal, as i have mentioned in the # remarks section. This function is similar to the printf() in C. It wraps around fmt.Sprintf(). 
This is a limited for now. We will add more functionalities like 'currency', 'date' etc. in  the future. 


The '-> #' part is just the string that gets printed as is. %x refers to hexadecimal. Similarly, %d for int and %s for strings.

2023-01-31 20:13 UTC, gthrone25 commented on sql-preview/functions/_posts/2023-01-26-sql-format.md
> +select _id, format("%s -> #%x", segment, value) as segment from segments;
Agree with @rachithrr, those are standard and he's defined them above. I think this is great!

2023-01-31 20:13 UTC, gthrone25 commented on sql-preview/functions/_posts/2023-01-26-sql-format.md
> +select format('id = %d , time = %v , ids = %d, strings = %s', _id, time, ids, strings) as description from segments;
Sorry Lisa, gonna have to gang up on you with @rachithrr  here as these are pretty standard. Thanks for adding this example. This helps highlight weird types for users! One q, we are sure the commas don't separate values? That could get very weird if spaces exist in values for Stringsets

2023-02-01 02:26 UTC, ljsinclair commented on sql-preview/functions/_posts/2023-01-26-sql-format.md
> +select _id, format("%s -> #%x", segment, value) as segment from segments;
No worries :D

2023-02-01 02:26 UTC, ljsinclair commented on sql-preview/functions/_posts/2023-01-26-sql-format.md
> +select format('id = %d , time = %v , ids = %d, strings = %s', _id, time, ids, strings) as description from segments;
No worries :D

2023-02-01 15:07 UTC, gthrone25 commented on sql-preview/functions/_posts/2023-01-26-sql-format.md
> +| id = 1 , time = 2023-01-01 00:00:00 +0000 UTC , ids = [1 6 9], strings = [blue green red] |
@rachithrr last Q, but you are sure commas don't return with sets? Seems weird if data had spaces in them, but just looking to confirm.

2023-02-01 22:17 UTC, rachithrr commented on sql-preview/functions/_posts/2023-01-26-sql-format.md
> +| id = 1 , time = 2023-01-01 00:00:00 +0000 UTC , ids = [1 6 9], strings = [blue green red] |
Nope. All these are run in the cli and pasted the outputs as is.

2023-02-01 23:05 UTC, ljsinclair commented on sql-preview/functions/_posts/2023-01-26-sql-format.md
> +| id = 1 , time = 2023-01-01 00:00:00 +0000 UTC , ids = [1 6 9], strings = [blue green red] |
FYI, on further testing, the time jump is caused by the INSERT INTO statement.
```
INSERT INTO segments(_id, time, ids, strings)
    VALUES (1, '2023-01-01', [6 , 1, 9], ['red', 'blue', 'green']);
```

2023-02-01 23:18 UTC, ljsinclair commented on sql-preview/functions/_posts/2023-01-26-sql-format.md
> +| id = 1 , time = 2023-01-01 00:00:00 +0000 UTC , ids = [1 6 9], strings = [blue green red] |
FYI, running the second SQL example has revealed a time-travel bug:
https://github.com/molecula/documentation/pull/315/files#

2023-02-01 23:43 UTC, ljsinclair commented
FYI this content added to https://github.com/FeatureBaseDB/featurebase-docs/tree/new-functions and will be merged when this is approved/merged

2023-02-01 23:43 UTC, rachithrr commented on sql-preview/functions/_posts/2023-01-26-sql-format.md
> +| id = 1 , time = 2023-01-01 00:00:00 +0000 UTC , ids = [1 6 9], strings = [blue green red] |
yeah, I asked @paddyjok about it. It's a known bug with epochs that is not related to FORMAT(). It should be fixed soon.  
Note that you get the same `3992` on `select`  statement as well.

2023-02-02 01:05 UTC, ljsinclair commented on sql-preview/functions/_posts/2023-01-26-sql-format.md
> +| id = 1 , time = 2023-01-01 00:00:00 +0000 UTC , ids = [1 6 9], strings = [blue green red] |
Yeah, it's pretty impressive :D

2023-02-02 14:13 UTC, gthrone25 approved these changes
Approved!

2023-02-02 14:14 UTC, gthrone25 commented
@ljsinclair need you to approve as you "requested changes"

2023-02-02 21:35 UTC, ljsinclair approved these changes

2023-02-02 22:03 UTC, merged